# Generated by Django 4.2.16 on 2024-10-11 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_commrnt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commrnt',
            new_name='Comment',
        ),
    ]
